spring.application.name=CodeSentinel
logging.file.name=logs/codesentinel.log
# Giới hạn kích thước tối đa cho TỪNG FILE upload (Ví dụ: 100MB)
spring.servlet.multipart.max-file-size=100MB

# Giới hạn tổng kích thước tối đa cho một REQUEST (Ví dụ: 100MB)
spring.servlet.multipart.max-request-size=100MB