spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            client-name: Facebook
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
                - public_profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration: 900000
      refresh-token-expiration: 2592000000
      issuer: CodeSentinel

  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

server:
  port: 8080

google:
  recaptcha:
    secret: ${RECAPTCHA_SECRET}
    url: "https://www.google.com/recaptcha/api/siteverify"