spring.application.name=CodeSentinel
logging.file.name=logs/codesentinel.log
# Giới hạn kích thước tối đa cho TỪNG FILE upload (Ví dụ: 100MB)
spring.servlet.multipart.max-file-size=100MB

# Giới hạn tổng kích thước tối đa cho một REQUEST (Ví dụ: 100MB)
spring.servlet.multipart.max-request-size=100MB

spring.security.oauth2.client.registration.facebook.client-id=2018992565377761
spring.security.oauth2.client.registration.facebook.client-secret=53b02ac08b529abffc99deb27210ebfa