package com.codesentinel.scan.domain.enums;

public enum FindingType {
    DANGEROUS_KEYWORD,
    COMMAND_EXECUTION,
    BASE64_OBFUSCATION,
    HEX_OBFUSCATION,
    INVISIBLE_UNICODE,
    SUSPICIOUS_RANDOM_STRING,
    STRING_OBFUSCATION,
    NETWORK_ACCESS,
    SUSPICIOUS_URL,
    DISCORD_WEBHOOK,
    IP_ADDRESS,
    REFLECTION_ABUSE,
    REFLECTION_CHAIN
}
